[build]
  # Répertoire de build
  publish = "frontend/build"
  # Commande de build
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"
  # Pas de télémétrie mais pas d'erreurs sur warnings
  CI = "false"
  # Désactive eslint warnings comme erreurs
  DISABLE_ESLINT_PLUGIN = "true"

# Redirections pour React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 